name: Docker Image CI

on:
  push:
    tags:
      ["v*.*.*", "v*.*.*-*"]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "./v2/uci"
          push: true
          tags: samagragovernance/uci-apis:${{ steps.vars.outputs.tag }}
          build-args: NPM_TOKEN=${{secrets.TOKEN}}